name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Build step
        uses: denoland/setup-deno@v1
      - name: Verify Deno installation
        run: deno --version 
      - name: Run Deno
        run: deno run --allow-net=api.notion.com --allow-env https://raw.githubusercontent.com/nickerionalt/notioneo-aft-assistant/main/src/main.ts
      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "naaa"
          entrypoint: "main.ts" # 📝 Update the entrypoint
          root: "."
