name: Notion Integration

# on: # Remove the first '#' in this line and select one or both options below removing the comments in line 7-8 or/and 11
  # Run automatically
  # schedule: # Make sure to uncomment the line below if you uncomment this line
    # - cron: "*/5 * * * *"
      
  workflow_dispatch:

jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
      - name: Install dependencies
        run: |
          node --version
          npm --version
          npm install
      - name: Trigger script
        env:
          INTEGRATION_TOKEN: 'secret_1znQ6olMQsv4LAUmiDUWxrZlAJ2hibu5Rut4LOVU0VB'  # Replace with the name of your Integration Token secret
        run: |
          node index_trigger.js  # Replace with the name of your script
